server:
  servlet:
    context-path: /EmployeePortal10
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/employeePortal
    username: root
    password: hdozwpeqvdqxtzwr
    driver-class-name : com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
  mail:
    host: smtp.gmail.com
    port: 587
    username: employee.portal.100@gmail.com
    password: hdozwpeqvdqxtzwr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true